name: Auto-update Pre-commit Hooks
description: Auto-updates pre-commit hooks and creates a PR.

inputs:
  base-branch:
    description: The base branch for the pull request
    default: "main"

outputs:
  changes-committed:
    description: 'Whether changes were committed'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash

    - name: Run pre-commit autoupdate
      run: pre-commit autoupdate
      shell: bash

    - name: Commit updated hooks
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b chore/update-precommit-hooks || git checkout chore/update-precommit-hooks
        git add .pre-commit-config.yaml
        if git commit -m "chore: auto-update pre-commit hooks"; then
          echo "changes-committed=true" >> "$GITHUB_OUTPUT"
          git push --set-upstream origin chore/update-precommit-hooks
        else
          echo "changed-committed=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Create Pull Request
      if: steps.autoupdate.outputs.changes-committed == "true"
      uses: peter-evans/create-pull-request@v7
      with:
        title: "chore: auto-update pre-commit hooks"
        body: "This PR was created automatically by a scheduled workflow to keep pre-commit hooks up to date."
        branch: chore/update-precommit-hooks
        base: ${{ inputs.base-branch }}
        labels: dependencies
